module.exports={
 PRODUCT_COLLECTION:'product',
 USER_COLLECTION:'user',
 CART_COLLECTION:'cart',
 ORDER_COLLECTION:'order',
 SHOP_COLLECTION:'shop',
 PRODUCER_COLLECTION:'producer',
 REQUIREMENT_collection:'requirement',
 WISHLIST_COLLECTION:"wishList",
 CLAIM_COLLECTION:"claims",
 ADMIN_COLLECTION:'admin'
}